version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "7000:80"
      - "443:443"
    volumes:
      - ./docker/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app:delegated
    depends_on:
      - app
    networks:
      - laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravelapp:latest
    container_name: laravelapp
    restart: unless-stopped
    working_dir: /var/www/app
    expose:
      - "9000"
    volumes:
      - ./:/var/www/app
      - ./.env.docker:/var/www/app/.env
      #- ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    depends_on:
      - db

  db:
    image: mysql:8.3
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: stockprices
      # MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD:
    volumes:
      - /dbdata:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - laravel

networks:
  laravel:
    name: laravel
    driver: bridge

volumes:
  dbdata:
    driver: local